/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DesignerDtoSchool model module.
 * @module model/DesignerDtoSchool
 * @version 1.0.0
 */
class DesignerDtoSchool {
    /**
     * Constructs a new <code>DesignerDtoSchool</code>.
     * @alias module:model/DesignerDtoSchool
     * @param major {String} 
     * @param year {Number} 
     * @param name {String} 
     */
    constructor(major, year, name) { 
        
        DesignerDtoSchool.initialize(this, major, year, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, major, year, name) { 
        obj['major'] = major;
        obj['year'] = year;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DesignerDtoSchool</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DesignerDtoSchool} obj Optional instance to populate.
     * @return {module:model/DesignerDtoSchool} The populated <code>DesignerDtoSchool</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DesignerDtoSchool();

            if (data.hasOwnProperty('major')) {
                obj['major'] = ApiClient.convertToType(data['major'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} major
 */
DesignerDtoSchool.prototype['major'] = undefined;

/**
 * @member {Number} year
 */
DesignerDtoSchool.prototype['year'] = undefined;

/**
 * @member {String} name
 */
DesignerDtoSchool.prototype['name'] = undefined;






export default DesignerDtoSchool;

