/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DesignerDtoSchool from './DesignerDtoSchool';
import DesignerDtoUser from './DesignerDtoUser';
import Id from './Id';

/**
 * The DesignerDto model module.
 * @module model/DesignerDto
 * @version 1.0.0
 */
class DesignerDto {
    /**
     * Constructs a new <code>DesignerDto</code>.
     * @alias module:model/DesignerDto
     * @param id {module:model/Id} 
     * @param photo {String} 
     * @param selfIntroduction {String} 
     * @param user {module:model/DesignerDtoUser} 
     */
    constructor(id, photo, selfIntroduction, user) { 
        
        DesignerDto.initialize(this, id, photo, selfIntroduction, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, photo, selfIntroduction, user) { 
        obj['id'] = id;
        obj['photo'] = photo;
        obj['self_introduction'] = selfIntroduction;
        obj['user'] = user;
    }

    /**
     * Constructs a <code>DesignerDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DesignerDto} obj Optional instance to populate.
     * @return {module:model/DesignerDto} The populated <code>DesignerDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DesignerDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = Id.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('photo')) {
                obj['photo'] = ApiClient.convertToType(data['photo'], 'String');
            }
            if (data.hasOwnProperty('self_introduction')) {
                obj['self_introduction'] = ApiClient.convertToType(data['self_introduction'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = DesignerDtoUser.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('contact_availability')) {
                obj['contact_availability'] = ApiClient.convertToType(data['contact_availability'], 'Boolean');
            }
            if (data.hasOwnProperty('school')) {
                obj['school'] = DesignerDtoSchool.constructFromObject(data['school']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Id} id
 */
DesignerDto.prototype['id'] = undefined;

/**
 * @member {String} photo
 */
DesignerDto.prototype['photo'] = undefined;

/**
 * @member {String} self_introduction
 */
DesignerDto.prototype['self_introduction'] = undefined;

/**
 * @member {module:model/DesignerDtoUser} user
 */
DesignerDto.prototype['user'] = undefined;

/**
 * @member {Boolean} contact_availability
 */
DesignerDto.prototype['contact_availability'] = undefined;

/**
 * @member {module:model/DesignerDtoSchool} school
 */
DesignerDto.prototype['school'] = undefined;






export default DesignerDto;

