/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DesignerDtoUser model module.
 * @module model/DesignerDtoUser
 * @version 1.0.0
 */
class DesignerDtoUser {
    /**
     * Constructs a new <code>DesignerDtoUser</code>.
     * @alias module:model/DesignerDtoUser
     * @param username {String} 
     * @param email {String} 
     * @param nickname {String} 
     * @param name {String} 
     * @param profile {String} 
     */
    constructor(username, email, nickname, name, profile) { 
        
        DesignerDtoUser.initialize(this, username, email, nickname, name, profile);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email, nickname, name, profile) { 
        obj['username'] = username;
        obj['email'] = email;
        obj['nickname'] = nickname;
        obj['name'] = name;
        obj['profile'] = profile;
    }

    /**
     * Constructs a <code>DesignerDtoUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DesignerDtoUser} obj Optional instance to populate.
     * @return {module:model/DesignerDtoUser} The populated <code>DesignerDtoUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DesignerDtoUser();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
DesignerDtoUser.prototype['username'] = undefined;

/**
 * @member {String} email
 */
DesignerDtoUser.prototype['email'] = undefined;

/**
 * @member {String} nickname
 */
DesignerDtoUser.prototype['nickname'] = undefined;

/**
 * @member {String} name
 */
DesignerDtoUser.prototype['name'] = undefined;

/**
 * @member {String} profile
 */
DesignerDtoUser.prototype['profile'] = undefined;

/**
 * @member {String} phone
 */
DesignerDtoUser.prototype['phone'] = undefined;






export default DesignerDtoUser;

