/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Id from './Id';

/**
 * The InlineObject4 model module.
 * @module model/InlineObject4
 * @version 1.0.0
 */
class InlineObject4 {
    /**
     * Constructs a new <code>InlineObject4</code>.
     * @alias module:model/InlineObject4
     */
    constructor() { 
        
        InlineObject4.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject4} obj Optional instance to populate.
     * @return {module:model/InlineObject4} The populated <code>InlineObject4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject4();

            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = Id.constructFromObject(data['category_id']);
            }
            if (data.hasOwnProperty('preview_thumbnail_id')) {
                obj['preview_thumbnail_id'] = Id.constructFromObject(data['preview_thumbnail_id']);
            }
            if (data.hasOwnProperty('detail_thumbnail_id')) {
                obj['detail_thumbnail_id'] = Id.constructFromObject(data['detail_thumbnail_id']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Id} category_id
 */
InlineObject4.prototype['category_id'] = undefined;

/**
 * @member {module:model/Id} preview_thumbnail_id
 */
InlineObject4.prototype['preview_thumbnail_id'] = undefined;

/**
 * @member {module:model/Id} detail_thumbnail_id
 */
InlineObject4.prototype['detail_thumbnail_id'] = undefined;

/**
 * @member {String} name
 */
InlineObject4.prototype['name'] = undefined;

/**
 * @member {String} description
 */
InlineObject4.prototype['description'] = undefined;






export default InlineObject4;

