/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Id from './Id';

/**
 * The InlineObject2 model module.
 * @module model/InlineObject2
 * @version 1.0.0
 */
class InlineObject2 {
    /**
     * Constructs a new <code>InlineObject2</code>.
     * @alias module:model/InlineObject2
     * @param selfIntroduction {String} 
     * @param contactAvailability {String} 
     */
    constructor(selfIntroduction, contactAvailability) { 
        
        InlineObject2.initialize(this, selfIntroduction, contactAvailability);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, selfIntroduction, contactAvailability) { 
        obj['self_introduction'] = selfIntroduction;
        obj['contact_availability'] = contactAvailability;
    }

    /**
     * Constructs a <code>InlineObject2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject2} obj Optional instance to populate.
     * @return {module:model/InlineObject2} The populated <code>InlineObject2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject2();

            if (data.hasOwnProperty('photo_id')) {
                obj['photo_id'] = Id.constructFromObject(data['photo_id']);
            }
            if (data.hasOwnProperty('self_introduction')) {
                obj['self_introduction'] = ApiClient.convertToType(data['self_introduction'], 'String');
            }
            if (data.hasOwnProperty('contact_availability')) {
                obj['contact_availability'] = ApiClient.convertToType(data['contact_availability'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Id} photo_id
 */
InlineObject2.prototype['photo_id'] = undefined;

/**
 * @member {String} self_introduction
 */
InlineObject2.prototype['self_introduction'] = undefined;

/**
 * @member {String} contact_availability
 */
InlineObject2.prototype['contact_availability'] = undefined;






export default InlineObject2;

