/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject1 model module.
 * @module model/InlineObject1
 * @version 1.0.0
 */
class InlineObject1 {
    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:model/InlineObject1
     * @param username {String} login id
     * @param email {String} email
     * @param password {String} password
     * @param name {String} user real name
     * @param phone {String} phone number
     */
    constructor(username, email, password, name, phone) { 
        
        InlineObject1.initialize(this, username, email, password, name, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, email, password, name, phone) { 
        obj['username'] = username;
        obj['email'] = email;
        obj['password'] = password;
        obj['name'] = name;
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject1} obj Optional instance to populate.
     * @return {module:model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
            }
        }
        return obj;
    }


}

/**
 * login id
 * @member {String} username
 */
InlineObject1.prototype['username'] = undefined;

/**
 * email
 * @member {String} email
 */
InlineObject1.prototype['email'] = undefined;

/**
 * password
 * @member {String} password
 */
InlineObject1.prototype['password'] = undefined;

/**
 * user real name
 * @member {String} name
 */
InlineObject1.prototype['name'] = undefined;

/**
 * phone number
 * @member {String} phone
 */
InlineObject1.prototype['phone'] = undefined;

/**
 * image url
 * @member {String} profile
 */
InlineObject1.prototype['profile'] = undefined;






export default InlineObject1;

