/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Id from './Id';

/**
 * The InlineObject3 model module.
 * @module model/InlineObject3
 * @version 1.0.0
 */
class InlineObject3 {
    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:model/InlineObject3
     * @param categoryId {module:model/Id} 
     * @param name {String} 
     * @param description {String} 
     * @param summary {String} 
     * @param modification {Number} 
     * @param workday {Number} 
     * @param concept {Number} 
     */
    constructor(categoryId, name, description, summary, modification, workday, concept) { 
        
        InlineObject3.initialize(this, categoryId, name, description, summary, modification, workday, concept);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, categoryId, name, description, summary, modification, workday, concept) { 
        obj['category_id'] = categoryId;
        obj['name'] = name;
        obj['description'] = description;
        obj['summary'] = summary;
        obj['modification'] = modification;
        obj['workday'] = workday;
        obj['concept'] = concept;
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject3} obj Optional instance to populate.
     * @return {module:model/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('detail_thumbnail_id')) {
                obj['detail_thumbnail_id'] = Id.constructFromObject(data['detail_thumbnail_id']);
            }
            if (data.hasOwnProperty('thumbnail_ids')) {
                obj['thumbnail_ids'] = ApiClient.convertToType(data['thumbnail_ids'], [Id]);
            }
            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = Id.constructFromObject(data['category_id']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('modification')) {
                obj['modification'] = ApiClient.convertToType(data['modification'], 'Number');
            }
            if (data.hasOwnProperty('workday')) {
                obj['workday'] = ApiClient.convertToType(data['workday'], 'Number');
            }
            if (data.hasOwnProperty('concept')) {
                obj['concept'] = ApiClient.convertToType(data['concept'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Id} detail_thumbnail_id
 */
InlineObject3.prototype['detail_thumbnail_id'] = undefined;

/**
 * @member {Array.<module:model/Id>} thumbnail_ids
 */
InlineObject3.prototype['thumbnail_ids'] = undefined;

/**
 * @member {module:model/Id} category_id
 */
InlineObject3.prototype['category_id'] = undefined;

/**
 * @member {String} name
 */
InlineObject3.prototype['name'] = undefined;

/**
 * @member {String} description
 */
InlineObject3.prototype['description'] = undefined;

/**
 * @member {String} summary
 */
InlineObject3.prototype['summary'] = undefined;

/**
 * @member {Number} modification
 */
InlineObject3.prototype['modification'] = undefined;

/**
 * @member {Number} workday
 */
InlineObject3.prototype['workday'] = undefined;

/**
 * @member {Number} concept
 */
InlineObject3.prototype['concept'] = undefined;






export default InlineObject3;

