/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserMeDto from './UserMeDto';

/**
 * The SigninUserDto model module.
 * @module model/SigninUserDto
 * @version 1.0.0
 */
class SigninUserDto {
    /**
     * Constructs a new <code>SigninUserDto</code>.
     * @alias module:model/SigninUserDto
     * @param user {module:model/UserMeDto} 
     * @param token {String} jwt token
     */
    constructor(user, token) { 
        
        SigninUserDto.initialize(this, user, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user, token) { 
        obj['user'] = user;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>SigninUserDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SigninUserDto} obj Optional instance to populate.
     * @return {module:model/SigninUserDto} The populated <code>SigninUserDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SigninUserDto();

            if (data.hasOwnProperty('user')) {
                obj['user'] = UserMeDto.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserMeDto} user
 */
SigninUserDto.prototype['user'] = undefined;

/**
 * jwt token
 * @member {String} token
 */
SigninUserDto.prototype['token'] = undefined;






export default SigninUserDto;

