/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserMeDto model module.
 * @module model/UserMeDto
 * @version 1.0.0
 */
class UserMeDto {
    /**
     * Constructs a new <code>UserMeDto</code>.
     * @alias module:model/UserMeDto
     * @param id {String} 
     * @param email {String} 
     * @param username {String} 
     * @param name {String} 
     * @param nickname {String} 
     */
    constructor(id, email, username, name, nickname) { 
        
        UserMeDto.initialize(this, id, email, username, name, nickname);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, email, username, name, nickname) { 
        obj['id'] = id;
        obj['email'] = email;
        obj['username'] = username;
        obj['name'] = name;
        obj['nickname'] = nickname;
    }

    /**
     * Constructs a <code>UserMeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserMeDto} obj Optional instance to populate.
     * @return {module:model/UserMeDto} The populated <code>UserMeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserMeDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nickname')) {
                obj['nickname'] = ApiClient.convertToType(data['nickname'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
            }
            if (data.hasOwnProperty('email_verified')) {
                obj['email_verified'] = ApiClient.convertToType(data['email_verified'], 'Boolean');
            }
            if (data.hasOwnProperty('phone_verified')) {
                obj['phone_verified'] = ApiClient.convertToType(data['phone_verified'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserMeDto.prototype['id'] = undefined;

/**
 * @member {String} email
 */
UserMeDto.prototype['email'] = undefined;

/**
 * @member {String} username
 */
UserMeDto.prototype['username'] = undefined;

/**
 * @member {String} name
 */
UserMeDto.prototype['name'] = undefined;

/**
 * @member {String} nickname
 */
UserMeDto.prototype['nickname'] = undefined;

/**
 * @member {String} phone
 */
UserMeDto.prototype['phone'] = undefined;

/**
 * @member {String} profile
 */
UserMeDto.prototype['profile'] = undefined;

/**
 * @member {Boolean} email_verified
 */
UserMeDto.prototype['email_verified'] = undefined;

/**
 * @member {Boolean} phone_verified
 */
UserMeDto.prototype['phone_verified'] = undefined;






export default UserMeDto;

