/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTynidesigner);
  }
}(this, function(expect, SwaggerTynidesigner) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTynidesigner.DesignerDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DesignerDto', function() {
    it('should create an instance of DesignerDto', function() {
      // uncomment below and update the code to test DesignerDto
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be.a(SwaggerTynidesigner.DesignerDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be();
    });

    it('should have the property photo (base name: "photo")', function() {
      // uncomment below and update the code to test the property photo
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be();
    });

    it('should have the property selfIntroduction (base name: "self_introduction")', function() {
      // uncomment below and update the code to test the property selfIntroduction
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be();
    });

    it('should have the property user (base name: "user")', function() {
      // uncomment below and update the code to test the property user
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be();
    });

    it('should have the property contactAvailability (base name: "contact_availability")', function() {
      // uncomment below and update the code to test the property contactAvailability
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be();
    });

    it('should have the property school (base name: "school")', function() {
      // uncomment below and update the code to test the property school
      //var instane = new SwaggerTynidesigner.DesignerDto();
      //expect(instance).to.be();
    });

  });

}));
