/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTynidesigner);
  }
}(this, function(expect, SwaggerTynidesigner) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTynidesigner.InlineObject3();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineObject3', function() {
    it('should create an instance of InlineObject3', function() {
      // uncomment below and update the code to test InlineObject3
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be.a(SwaggerTynidesigner.InlineObject3);
    });

    it('should have the property detailThumbnailId (base name: "detail_thumbnail_id")', function() {
      // uncomment below and update the code to test the property detailThumbnailId
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailIds (base name: "thumbnail_ids")', function() {
      // uncomment below and update the code to test the property thumbnailIds
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property categoryId (base name: "category_id")', function() {
      // uncomment below and update the code to test the property categoryId
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property summary (base name: "summary")', function() {
      // uncomment below and update the code to test the property summary
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property modification (base name: "modification")', function() {
      // uncomment below and update the code to test the property modification
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property workday (base name: "workday")', function() {
      // uncomment below and update the code to test the property workday
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

    it('should have the property concept (base name: "concept")', function() {
      // uncomment below and update the code to test the property concept
      //var instane = new SwaggerTynidesigner.InlineObject3();
      //expect(instance).to.be();
    });

  });

}));
