/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DesignerDto from './model/DesignerDto';
import DesignerDtoSchool from './model/DesignerDtoSchool';
import DesignerDtoUser from './model/DesignerDtoUser';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import InlineObject4 from './model/InlineObject4';
import InlineObject5 from './model/InlineObject5';
import InlineResponse200 from './model/InlineResponse200';
import Pagination from './model/Pagination';
import Pagination1 from './model/Pagination1';
import SigninUserDto from './model/SigninUserDto';
import UserMeDto from './model/UserMeDto';
import AuthApi from './api/AuthApi';
import DesignerArtworksApi from './api/DesignerArtworksApi';
import DesignersApi from './api/DesignersApi';
import FilesApi from './api/FilesApi';
import SchoolsApi from './api/SchoolsApi';
import ServiceCategoriesApi from './api/ServiceCategoriesApi';
import ServicesApi from './api/ServicesApi';
import UploadsApi from './api/UploadsApi';


/**
* Tynidesigner_Api_Specification_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SwaggerTynidesigner = require('index'); // See note below*.
* var xxxSvc = new SwaggerTynidesigner.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SwaggerTynidesigner.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SwaggerTynidesigner.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SwaggerTynidesigner.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DesignerDto model constructor.
     * @property {module:model/DesignerDto}
     */
    DesignerDto,

    /**
     * The DesignerDtoSchool model constructor.
     * @property {module:model/DesignerDtoSchool}
     */
    DesignerDtoSchool,

    /**
     * The DesignerDtoUser model constructor.
     * @property {module:model/DesignerDtoUser}
     */
    DesignerDtoUser,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The Pagination model constructor.
     * @property {module:model/Pagination}
     */
    Pagination,

    /**
     * The Pagination1 model constructor.
     * @property {module:model/Pagination1}
     */
    Pagination1,

    /**
     * The SigninUserDto model constructor.
     * @property {module:model/SigninUserDto}
     */
    SigninUserDto,

    /**
     * The UserMeDto model constructor.
     * @property {module:model/UserMeDto}
     */
    UserMeDto,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The DesignerArtworksApi service constructor.
    * @property {module:api/DesignerArtworksApi}
    */
    DesignerArtworksApi,

    /**
    * The DesignersApi service constructor.
    * @property {module:api/DesignersApi}
    */
    DesignersApi,

    /**
    * The FilesApi service constructor.
    * @property {module:api/FilesApi}
    */
    FilesApi,

    /**
    * The SchoolsApi service constructor.
    * @property {module:api/SchoolsApi}
    */
    SchoolsApi,

    /**
    * The ServiceCategoriesApi service constructor.
    * @property {module:api/ServiceCategoriesApi}
    */
    ServiceCategoriesApi,

    /**
    * The ServicesApi service constructor.
    * @property {module:api/ServicesApi}
    */
    ServicesApi,

    /**
    * The UploadsApi service constructor.
    * @property {module:api/UploadsApi}
    */
    UploadsApi
};
