/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTynidesigner);
  }
}(this, function(expect, SwaggerTynidesigner) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTynidesigner.AuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthApi', function() {
    describe('authLogoutPost', function() {
      it('should call authLogoutPost successfully', function(done) {
        //uncomment below and update the code to test authLogoutPost
        //instance.authLogoutPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authMeGet', function() {
      it('should call authMeGet successfully', function(done) {
        //uncomment below and update the code to test authMeGet
        //instance.authMeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authMePointGet', function() {
      it('should call authMePointGet successfully', function(done) {
        //uncomment below and update the code to test authMePointGet
        //instance.authMePointGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authSigninPost', function() {
      it('should call authSigninPost successfully', function(done) {
        //uncomment below and update the code to test authSigninPost
        //instance.authSigninPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authSignupPost', function() {
      it('should call authSignupPost successfully', function(done) {
        //uncomment below and update the code to test authSignupPost
        //instance.authSignupPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
