/**
 * Swagger Tynidesigner
 * Tynidesigner Api Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTynidesigner);
  }
}(this, function(expect, SwaggerTynidesigner) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTynidesigner.DesignersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DesignersApi', function() {
    describe('designersIdArtworksGet', function() {
      it('should call designersIdArtworksGet successfully', function(done) {
        //uncomment below and update the code to test designersIdArtworksGet
        //instance.designersIdArtworksGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('designersIdGet', function() {
      it('should call designersIdGet successfully', function(done) {
        //uncomment below and update the code to test designersIdGet
        //instance.designersIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('designersIdServicesGet', function() {
      it('should call designersIdServicesGet successfully', function(done) {
        //uncomment below and update the code to test designersIdServicesGet
        //instance.designersIdServicesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('designersPost', function() {
      it('should call designersPost successfully', function(done) {
        //uncomment below and update the code to test designersPost
        //instance.designersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
